baseURL = 'https://skoolink.id/'
languageCode = 'en-us'
title = 'Skoolink'
theme = 'skoolink' 

[params]
logo = "/img/logoskoolink.svg"
favicon = "/img/favicon.png"
defaultImage = "/img/logo_skoolink.og.png" 
email = "hello@skoolink.id"
phone = "+62 877-0101-1100"
 
  [[params.social]]
  name = "twitter"
  url = "https://twitter.com"
  icon = "fa-x-twitter"

  [[params.social]]
  name = "facebook"
  url = "https://www.facebook.com/"
  icon = "fa-facebook-f"

  [[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/"
  icon = "fa-instagram"

  [[params.social]]
  name = "github"
  url = "https://www.github.com/"
  icon = "fa-github"


[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Tentang"
  url = "#section-about"
  weight = 2

  [[menu.main]]
  name = "Fitur"
  url = "#section-feature"
  weight = 3

  [[menu.main]]
  name = "Harga"
  url = "#section-pricing"
  weight = 4

  [[menu.main]]
  name = "Testimonial"
  url = "#section-testimonial"
  weight = 5

  [[menu.main]]
  name = "Blog"
  url = "#section-blog"
  weight = 6

  [[menu.main]]
  name = "Kontak"
  url = "#section-kontak"
  weight = 7

  [[menu.primary]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.primary]]
  name = "Tentang"
  url = "#section-about"
  weight = 2

  [[menu.primary]]
  name = "Fitur"
  url = "#section-feature"
  weight = 3

  [[menu.primary]]
  name = "Pricing"
  url = "#section-pricing"
  weight = 4

  [[menu.primary]]
  name = "Contact"
  url = "/contact"
  weight = 5

  [[menu.utility]]
  name = "Signup"
  url = "/signup"
  weight = 1

  [[menu.utility]]
  name = "Login"
  url = "/login"
  weight = 2

  [[menu.utility]]
  name = "404 Not Found"
  url = "/404.html"
  weight = 3

  [[menu.utility]]
  name = "Password Reset"
  url = "/reset-password"
  weight = 4

paginate = 10


[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

defaultContentLanguage = "id"
timeZone = "Asia/Jakarta"


[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 80


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
    
 [outputs]
home = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 